name: Terraform CI/CD

on:                # 👈 required event triggers
  push:
    branches:
      - main
  pull_request:     # run checks on PRs (plan only, no apply)
  workflow_dispatch:

permissions:
  contents: read
  security-events: write   # needed for SARIF upload

jobs:
  security-scan:
    name: tfsec Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tfsec
        run: |
          curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        id: tfsec
        run: |
          mkdir -p reports
          tfsec --format json --out reports/tfsec.json || true
          tfsec --format sarif --out reports/tfsec.sarif || true

          if [[ -s reports/tfsec.json ]]; then
            CRITICAL_COUNT=$(jq '[.results[] | select(.severity=="CRITICAL")] | length' reports/tfsec.json)
          else
            CRITICAL_COUNT=0
          fi

          echo "Critical findings: $CRITICAL_COUNT"
          echo "critical_count=$CRITICAL_COUNT" >> $GITHUB_OUTPUT

      - name: Upload tfsec SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/tfsec.sarif

      - name: Fail if critical findings exist
        if: steps.tfsec.outputs.critical_count != '0'
        run: |
          echo "❌ Critical findings detected. Deployment blocked."
          exit 1

  deploy:
    name: Terraform Deploy
    needs: security-scan
    runs-on: ubuntu-latest
    if: needs.security-scan.outputs.critical_count == '0' && github.ref == 'refs/heads/main'

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
