jobs:
  security-scan:
    name: tfsec Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # ✅ required for SARIF upload

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tfsec
        run: |
          curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        id: tfsec
        run: |
          mkdir -p reports
          tfsec --format json --out reports/tfsec.json || true
          tfsec --format sarif --out reports/tfsec.sarif || true

          if [[ -s reports/tfsec.json ]]; then
            CRITICAL_COUNT=$(jq '[.results[] | select(.severity=="CRITICAL")] | length' reports/tfsec.json)
          else
            CRITICAL_COUNT=0
          fi

          echo "Critical findings: $CRITICAL_COUNT"
          echo "critical_count=$CRITICAL_COUNT" >> $GITHUB_OUTPUT

      - name: Upload tfsec SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/tfsec.sarif

      - name: Fail if critical findings exist
        if: steps.tfsec.outputs.critical_count != '0'
        run: |
          echo "❌ Critical findings detected. Deployment blocked."
          exit 1
