name: Auto Install Terraform and Run tfsec

on:
  workflow_dispatch:  # Manual trigger in GitHub UI

permissions:
  security-events: write
  contents: read

jobs:
  tfsec:
    name: Scan Terraform with tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Automatically install Terraform
        run: |
          echo "Installing Terraform..."
          TERRAFORM_VERSION="1.8.5"
          curl -sSLo terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Run terraform init (without backend)
        run: terraform init -backend=false

      - name: Install tfsec
        run: |
          echo "Installing tfsec..."
          curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          tfsec --version

      - name: Run tfsec and generate SARIF + HTML reports
        run: |
          mkdir -p tfsec-reports
          tfsec . --format sarif > tfsec-reports/tfsec-results.sarif
          tfsec . --format html > tfsec-reports/tfsec-report.html

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec-reports/tfsec-results.sarif

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-html-report
          path: tfsec-reports/tfsec-report.html
