name: tfsec Terraform Security Scan

on:
  push:
    paths:
      - '**/*.tf'
  pull_request:
    paths:
      - '**/*.tf'

permissions:
  security-events: write
  contents: read

jobs:
  tfsec:
    name: Run tfsec Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Terraform (optional, but good practice)
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform modules
        run: terraform init -backend=false

      - name: Install tfsec
        run: |
          curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - name: Terraform Init
        run: terraform init

      - name: Run tfsec and generate reports
        run: |
          mkdir -p tfsec-reports
          tfsec . --format sarif > tfsec-reports/tfsec-results.sarif
          tfsec . --format html > tfsec-reports/tfsec-report.html

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec-reports/tfsec-results.sarif

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-html-report
          path: tfsec-reports/tfsec-report.html
